### ISSUE TITLE
Add "hidden" checkbox to fieldtype images item.

### ISSUE THREAD

**Issue by theo222** [processwire/processwire-requests#117]
Please add a way to hide / unpublish a single image temporarily instead of deleting (trashing) the entire image + text information. 

A checkbox for this would be great. 

Thank you.

**Comment by matjazpotocnik** [comment]
@theo222, since we now have custom fields support for file and image fields (https://processwire.com/blog/posts/pw-3.0.142/), perhaps you can add the checkbox yourself?

**Comment by theo222** [comment]
Thank you.

**Comment by ryancramerdesign** [comment]
@theo222 @matjazpotocnik You could use a custom field for this, but unless you need custom fields for other things also, the "tags" feature is a good way to handle this also. I usually have a predefined tag named "hidden" that I filter out on the front end. 
~~~~~
foreach($page->images as $image) {
  if($image->hasTag('hidden')) continue;
 // otherwise render the image
}
~~~~~
Or if I want it to do this for all files/images fields, then a simple hook to `FieldtypeFile::formatValue` in /site/ready.php can remove them automatically:
~~~~~
$wire->addHookAfter('FieldtypeFile::formatValue', function($event) {
  $pagefiles = $event->return;
  foreach($pagefiles as $pagefile) {
    if($pagefile->hasTag('hidden')) $pagefiles->removeQuietly($pagefile);
  }
}); 
~~~~~
Edit: there was a typo in my code example above, fixed.
