### ISSUE TITLE
Configurable default "from" address for WireMail

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#122]
### Short description of the enhancement

Currently WireMail falls back to the $config->adminEmail address when the from() method is not used to give a from address. This can happen when modules use WireMail, such as [LoginRegister](https://github.com/ryancramerdesign/LoginRegister). 

But the adminEmail address is for receiving error notices, so it is usually the address of the developer. In most cases, mail sent via WireMail should not be perceived as coming from the developer, but should be from some generic email address associated with the website domain.

Could we please have a WireMail config setting to define the default "from" address, to be used when no from address is specified in the from() method?

**Comment by teppokoivula** [comment]
+1 for this, definitely something we need. For us, for an example, $config->adminEmail is an internal support / error tracking address that should never be visible to end-users. For that purpose there's a separate no-reply address :)

Just for the record, at least WireMailSwiftmailer has it's own setting for this. Not sure about WireMailSMTP.

**Comment by horst-n** [comment]
Have it too. Also extra settings for reply-to and errors-to defaults, optional. 😃

**Comment by szabeszg** [comment]
Another example is Forgot Password module, see discussion:
https://processwire.com/talk/topic/13128-wiremail-configuration-for-recover-password-on-localhost/
Instead of `'processwire@' . $this->localhost` we should have a configurable fallback as Robin described above.

I even propose that asking for this email address should be part of the ProcessWire installer to ensure that it gets proper attention.

**Comment by deponeWD** [comment]
+1 for this feature request.

My suggestion is to include a `systemEmail` into the `config.php` like the `adminEmail`:

`$config->systemEmail = 'user@website.com';`

For some providers e-mails sent from the same address as they are received are marked as spam and will not be delivered. Therefore there is no error-reporting which makes the feature unusable.

**Comment by teppokoivula** [comment]
Cross-referencing https://github.com/processwire/processwire-issues/issues/725. In my opinion there should be a configurable outbound email address, so that we don't have to assume that the host, for an example, is a valid and properly configured email domain.

Considering what @horst-n said above it might even make sense to have multiple addresses:

- fromEmail (or perhaps senderEmail, outboundEmail, systemEmail.. although some form of 'from' would in my opinion be most obvious here)
- replyToEmail
- errorsToEmail

Either way, just defining the outbound address would be awesome. Thanks for considering this as a potential addition, @ryancramerdesign :)

**Comment by ryancramerdesign** [comment]
@Toutouwai @teppokoivula This is already supported by a $config property `$config->wireMail('from', 'you@domain.com');` and it is populated by the WireMailTools ($mail API var) for any messages PW sends. But I'm guessing that it may be getting replaced with blank or `$config->adminEmail` in cases of other modules that might be populating the from address. 

For cases where other modules might be setting `from` to be blank, then it could fallback to the `$config->adminEmail`. I'll add an update to the WireMail class that makes it perform a second check in the `$config->wireMail` to get around that case. 

I can only find one case where a core module is falling back to `$config->adminEmail` (rather than blank) and that is ProcessForgotPassword, for cases when no from email has been specified with the forgot-password settings. This is a simple fix.

I'll put in both of these updates today, which should prevent `$config->adminEmail` from being used as a default fallback for WireMail except in cases where its being done by a 3rd party module or when there is no other fallback available.

**Comment by Toutouwai** [comment]
Thanks @ryancramerdesign, `$config->wireMail` didn't exist when this request was opened and it must have been added later without my being aware of it.
