### ISSUE TITLE
 Allow user accounts to be disabled

### ISSUE THREAD

**Issue by gmclelland** [processwire/processwire-requests#140]
### Short description of the enhancement

Allow user accounts to be disabled.

### Current vs. suggested behavior

Currently when I need to disable a user's access, I have to remove all roles from the user.

I suggest adding a radio inputfields to the user template to indicate whether the user account is disabled or active/blocked(Drupal terminology).

### Why would the enhancement be useful to users?

Disabling/blocking a user account would prevent that user from logging in to the admin area.

When you're ready to re-enable the user, you don't have to remember what specific roles to apply.

Here is what it looks like in Drupal:
![admin city of mansfield texas 2017-12-07 09-32-54](https://user-images.githubusercontent.com/40570/33723210-ad9d3548-db31-11e7-84be-576411082a5d.jpg)

**Comment by adrianbj** [comment]
I agree, this could be very useful. I actually thought it would be a simple matter of setting the user to unpublished (which I did via the API since there is no other way), but it seems like the status is ignored for users. Would it be a simple matter of respecting the status and adding the pub/unpub action button to the users page?

**Comment by Toutouwai** [comment]
A big +1 for both the allowing of users to be disabled, and for implementing support for unpublished users. And it makes sense to me that these be the same thing - it's a perfect fit for the concept of published/unpublished.

I use unpublished status for enabling/disabling front-end users and it works great but it currently requires some workarounds such as [this module](https://github.com/BitPoet/SaveUserUnpublished) and some additional hacky stuff to deal with the password field.

Unfortunately the core login allows access to unpublished users, as Adrian mentions above.

**Comment by ryancramerdesign** [comment]
I agree, we should prevent login if the user has unpublished permission, as this could be convenient for API side stuff. But the problem is that unpublished status is already used for other things, like determining when a password is required vs. optional, in the user editor. So to support this, I think we'd be better off making it use the "hidden" status for this purpose, and disable login if the user has either unpublished or hidden status. An alternative to hidden status is to have it recognize a role with a specific name like "login-disabled", and disable login when the user has the role. What you guys think would be preferable (hidden status, or named role)?

**Comment by adrianbj** [comment]
I'd prefer if it could be the unpublished status - that seems more semantically correct. I would always feel a little unsafe setting it to hidden because in PW a hidden page is still viewable if you have the URL - I know it's not the same, but I like consistency and I think this would break this slightly. 

Do you think you could the `published` datetime to determine whether a password is required vs optional in the user editor? If it's `NULL` then we know that the user has never been published. Would that work ok?

**Comment by Toutouwai** [comment]
I agree with Adrian. 

From what I've seen, I think the password inputfield is the only thing currently affected by the unpublished status for users. Instead of being based on the user's unpublished status, couldn't the password inputfield be set to required and forced open only if the `data` column (the `hash` value) for the user's password is empty?

In my workaround I am doing this:

````php
$this->addHookBefore('ProcessUser::executeEdit', $this, 'beforeProcessUserEdit');

/**
 * Make password inputfield not required and collapsed for unpublished users
 */
public function beforeProcessUserEdit() {

    // Get the user being edited
    $edited_user = $this->users->get((int) $this->input->id);
    // Early return if no password has been set (i.e. new user)
    if(!$edited_user->pass->hash) return;

    // Password inputfield not required
    $this->addHookBefore('Field(name=pass)::getInputfield', function(HookEvent $event) {
        $field = $event->object;
        $field->required = false;
    });

    // Add script to collapse password inputfield
    $this->addHookAfter('ProcessPageEdit::execute', function(HookEvent $event) {
        $out = $event->return;
        $out .= "
<script>
$(function(){
    $('.InputfieldPassword').addClass('collapsed1 InputfieldStateCollapsed');
});
</script>
";
        $event->return = $out;
    });

}
````

**Comment by ryancramerdesign** [comment]
I agree that unpublished users shouldn't be able to login, and have added that (should appear in the next commit). As for how to implement an interactively configured "login disabled" state, I looked at the status options (unpublished, hidden, etc.) but decided it was better to use a role for the purpose. Beyond what I mentioned before about unpublished status already having a different purpose, status (any status) is not something you interactively edit with these other Page types, so would have had to add a "login disabled" checkbox manually to the editor. Most folks don't need it (like me), so don't want to add add stuff for people to look at, when don't need it. Would rather have the option available for people that need it, and not present when you don't. Another is access control and user-admin permissions, and the roles field is already access controlled for these. So using a role nicely fits right in with that model. Lastly, using roles provides a little more flexibility, like if you want to exclude everyone in a role temporarily, or something like that. I'll push the updates here shortly. But it all seems to work well in testing here.

**Comment by gmclelland** [comment]
Sorry Ryan, but I'm a little confused.  Are you saying that you added the ability to unpublish users and unpublished users will not be able to login to Processwire?  That sounds logical and it's easy to explain...  "To prevent users from logging in, unpublish the user just like you would unpublish a page in Processwire."

I'm confused about the roles.  Does this mean I need to add some kind of special role to my users, or are talking about when you're trying to find the users that are disabled from logging in via the PW api you need to look for the hidden status?

**Comment by ryancramerdesign** [comment]
An unpublished user is one that you've created, but haven't yet populated all the details for them. That's always been the case, and I was just saying that I agree, that type of user shouldn't be able to login until they are "published". 

Hidden status plays no part of the updates. It was just something I was contemplating earlier, but decided against it because it would have required a hook adding a field, showing it even if you didn't want it, and it would have needed to have additional access control logic for non-superusers that have user-admin permission. 

The way it's setup is that you can define which roles are not allowed to login (via a $config->loginDisabledRoles setting), and then if a user has one of those roles, they can't login. The default value of that config setting is one role, named "login-disabled". So if you create a role named "login-disabled", and add it to a user, and they will no longer be able to login.

**Comment by adrianbj** [comment]
> status (any status) is not something you interactively edit with these other Page types. Most folks don't need it (like me), so don't want to add add stuff for people to look at, when don't need it.

I know you already have a solution in place, but enabling the pub/unpub page list action on user pages would be a simple way of making this possible without needing to add a Settings tab.

Also, I am curious what happens if you are using the approach described here: https://processwire.com/blog/posts/processwire-core-updates-2.5.14/#multiple-templates-or-parents-for-users - do these pages have the pub/unpub actions and Settings tab disabled? If these are available is it going to confuse anything with the new role-based disabling you've just added?

**Comment by ryancramerdesign** [comment]
There are no changes to the page editor for users (whether using multiple templates or not). The configuration is isolated to the Roles field, which was already present and appears as it always has. The change is that if a user has a role that you've defined to prevent their login, the $session->login() function now recognizes that and will refuse the login.

**Comment by gmclelland** [comment]
Thank you for the explanations Ryan.  I guess I'm still not clear as to why we can't just unpublish a user that has already been published to prevent them from logging in?

That way we can also visually see from the page tree and Listers what users are unpublished by looking for the ~~strikethrough~~.

**Comment by ryancramerdesign** [comment]
If you have some way to unpublish a user, then it will have that effect (they won't be able to login), but that's not the purpose of it. What I wrote in the previous two messages are reasons why unpublished status should not be redefined purely as a toggle for dictating user login access. The purpose of the roles field is to define access.

**Comment by adrianbj** [comment]
Ryan,

I just set up the alternate user template / parent page approach and updated to the latest PW dev. I can now actually use pub/unpub to achieve @gmclelland 's original goal. That's because these pages have the ability to easily change the pub/unpub status via the settings tab or the page list actions. I still think this is the ideal approach - it's a shame it's so tedious to set up. READ BELOW for update - this now seems to work for regular users as well!

![image](https://user-images.githubusercontent.com/871211/33949793-8431252c-dfdf-11e7-8970-dd23a4d10c96.png)

![image](https://user-images.githubusercontent.com/871211/33949798-86807698-dfdf-11e7-897d-63367462804f.png)

Actually, just noticed that something in the process of setting up the alternate user template system has resulted in me now being able to set the status of a regular user to unpublished which actually works to prevent them logging in. See in this screenshot that this is a regular user with regular parent page and user template:

![image](https://user-images.githubusercontent.com/871211/33950747-03d0729a-dfe2-11e7-893b-b4a318fefae9.png)

**Comment by adrianbj** [comment]
Just a final follow up - @gmclelland if you want to easily be able to set a user to unpublished, simply set Advanced mode to true in config.php and then on the `user` template System tab, uncheck the "Disable Settings tab" option.

The big problem of course is that now you will need to reset the user's password because of that requirement that Ryan mentions above. The way around this is using the hacky hook in the module that @Toutouwai mentions above - not ideal I guess :)

**Comment by ryancramerdesign** [comment]
That's fine if you want to use it that way, but again that's not the purpose of it, so I don't recommend it. Of course it makes sense that an unpublished user shouldn't be able to login (because it hasn't been fully created), but it doesn't make sense to change its meaning to be redefined as "allowed to login" toggle. User access is the function of roles. 

Lets say you are using users as authors for articles, and you have an author that you no longer want to be able to login and add new posts, but you still want them to appear as the author for their existing posts. You are screwed if using unpublished status, this is why it's bad to mix up the meaning of page status. Or lets say you have a module that enables users to create their own accounts, and they go from unpublished to published once confirmed (via email or social oauth). Those would get mixed up with your intended "login disabled" accounts. So yes it makes sense that unpublished prevents login as a side effect, but it doesn't make sense for that to be the defined purpose of it. So I'd instead suggest using the new feature added in the linked commit for this purpose rather than repurposing unpublished status. It'll give you greater flexibility long term and is less likely to interfere with anything else.

**Comment by adrianbj** [comment]
> Lets say you are using users as authors for articles, and you have an author that you no longer want to be able to login and add new posts, but you still want them to appear as the author for their existing posts.

Assuming you mean if you want to have a page of info about that user that is linked from the article? Otherwise, I don't see why you could still grab their name and other fields to display along with the article. 

That said, I do definitely see where you are coming from regarding using a role for controlling this. 

Sorry if I was seeming obstinate in my goal for using unpublished to handle this - apologies!

**Comment by gmclelland** [comment]
> Sorry if I was seeming obstinate in my goal for using unpublished to handle this - apologies!

That goes for me as well.  Thanks everyone for the explanations!

**Comment by ryancramerdesign** [comment]
> Assuming you mean if you want to have a page of info about that user that is linked from the article? Otherwise, I don't see why you could still grab their name and other fields to display along with the article.

Take processwire.com for example, which has a tutorials section, and it shows a short bio and photo of the author (user) that created it. Fields that the author can populate in their profile. Standard in PW is that editors can view content on unpublished pages while guests cannot. An unpublished page indicates a page where you don't want the content published on your site. So this becomes a problem if we've redefined the meaning of unpublished to be "cannot login". Yes we could override that and use the unpublished content anyway, but at that point we've changed the meaning of unpublished. Maybe not a big deal for an individual installation that you control, but a problem as a core strategy. 

Hidden status is slightly better, but isn't ideal either, as the meaning of that is whether something can appear in searches and lists, etc. Taking our previous example, if you are listing out an index of users as authors of blog posts or something, and the user stops appearing there when they should, simply because they aren't allowed to login anymore. 

By using a separate role, we don't change the meaning of, or conflict with anything else. I do understand the desire to have a different appearance for the login-disabled users in the Users Lister. While it's a simple matter to filter by role, if you still wanted a different appearance for those users, and didn't need the hidden status for anything related to users, you might use a simple Pages::saveReady hook to add hidden status to users with the login-disabled role, and remove it from users that don't have it. I don't think the core should do that for the reasons mentioned earlier, but for an individual installation, that compromise might provide the desired visual feedback in the users list.

**Comment by gmclelland** [comment]
Hi Ryan,
I went to try out the new user role and ran into a problem.  I tried to create a login-disabled role, but now it shows the following any time I edit any role.

![roles](https://user-images.githubusercontent.com/40570/34113846-b1498c84-e3d6-11e7-9533-7397f046e843.jpg)

No php errors are displayed in the TracyDebugger.

Here is what my roles page looks like:
![rolespage](https://user-images.githubusercontent.com/40570/34113885-cdb831cc-e3d6-11e7-9262-2959ae17a1fd.jpg)

When I upgraded by development site, it works fine.  The production website is what is showing the error.

Anyone have any ideas or suggestions?

**Comment by gmclelland** [comment]
forgot to mention the full error message when trying to edit any role:

Unknown Selector operator: '' -- was your selector value properly escaped? (in /wire/core/Selectors.php line 378)

**Comment by ethanbeyer** [comment]
I usually get this error when I have a function with a hook that is looking for a page with an ID that isn’t an integer (like the database export module) or things like that. Check your modules for hooks that might be looking for a user’s properties that aren’t set with this new Role.

**Comment by gmclelland** [comment]
Thanks for responding @ethanbeyer!  I managed to solve the problem by deleting a permission that didn't have a page name for some reason.

I noticed if I looked at the page tree under Admin>Access>Permissions> there was one permission that didn't have a page name, only an id.  That was the only difference I could tell between my development and production sites, so I deleted the permission.  After that I tried to edit a role and everything worked fine.  I even tested the new login-disabled role and it worked correctly preventing the user from logging in.

I'm not sure what caused the permission to not have a page name, but I'm glad it works now.

I'm going to close this issue now since this functionality has been added to core.  Thanks @ryancramerdesign

**Comment by jorunkel** [comment]
This technique should be added to the documentation. I googled for how to disable users and had to read through all this issue - and effectively the source code - in order to find the solution.

**Comment by jmartsch** [comment]
@jorunkel I think it would be best to open a new issue for this and refer to this issue here.

**Comment by jorunkel** [comment]
@jmartsch Thanks for the hint, I just do so.
