### ISSUE TITLE
Add a special hook for TracyDugger so that it can debug other modules all the time.

### ISSUE THREAD

**Issue by gideonso** [processwire/processwire-requests#165]
### Short description of the enhancement

Add a special hook for module so that some modules such as TracyDebugger can load before other modules.

### Current vs. suggested behavior

Now modules load with random order. It is alright in most cases. One of the cases that causes problem is that when you want to debug a module with TracyDebugger but your module loads before Tracy, then Tracy is not able to debug the module.  

### Why would the enhancement be useful to users?

I think it is very good to ensure Tracy always load before other modules. It helps developers to debug modules.

**Comment by adrianbj** [comment]
A big +1 for this. 

At a minimum I would like to see Tracy load before all "site" modules. I think this would be fairly simple to implement.

A more powerful solution would be to have an option where I could include the tracy core files before anything else - possible even most of the PW core. This would make it possible to use Tracy to debug core modules and even other core files.

@gideonso - in the meantime, try this solution and let us know if it works as expected.

1) Comment out this line: https://github.com/adrianbj/TracyDebugger/blob/b40f8f9df59b905126e6da3f266dcac1f76f5b1e/TracyDebugger.module#L633

2) Add this line:
```
require_once  $config->paths->siteModules.'TracyDebugger/tracy-master/src/tracy.php';
```
here:
https://github.com/processwire/processwire/blob/d9b30167c7cdf08fc093e007b01a8b871ed08417/index.php#L34

What I don't understand right now is the need to comment out the first one since it uses `require_once` I would have thought it wouldn't try to load twice, but that's not important for now. At least this should let you debug pretty much anything in the PW core. 

@ryancramerdesign - please consider a way we can implement this without hacking the core index.php file! You might even find it useful yourself ;)

**Comment by adrianbj** [comment]
PS @ryancramerdesign - a really simple solution for you would be to simply add that line to the core index.php file. Obviously modified to do a file_exists check before requiring. Would that be ok?

Of course we can't check if the Tracy module is installed because we don't have that info yet, but we can see if the file exists. Or do you think there might be a better solution?

Thanks for your time on this.

**Comment by adrianbj** [comment]
As usual, I have gotten too excited and a little ahead of myself here :)

We do need a way to NOT load that file based on some logic in the TracyDebugger.module file and module settings (when Tracy is disabled, etc). I have no idea how we can do that while still loading the file early when needed. Any ideas?

**Comment by adrianbj** [comment]
@gideonso - you will also need to load these files in index.php as well
```
/includes/TD.php
/includes/ShortcutMethods.php
```

**Comment by teppokoivula** [comment]
Would it be enough if there was a way to load specific module(s) early on based on, say, a config setting? I'm thinking of a kind of a "manual module load order" or "priority modules" setting.

This would, in my opinion, be preferable over hardcoded, module-specific paths in the core. I get that, at least for the time being, Tracy would be the main reason for this, but I'd still rather see a universal solution.

Giving the user the option to adjust the module load order without changing core files could be a nice addition for other use cases too, and – in my opinion – tweaking a config setting shouldn't be too big of a step for, say, Tracy users.

**Comment by gideonso** [comment]
@teppokoivula This is indeed a good idea.

**Comment by ryancramerdesign** [comment]
@adrianbj @teppokoivula @gideonso ProcessWire has had support for this and TracyDebugger has been using it for awhile (though I'm guessing we didn't have it when this feature was requested). 

It is specified with an integer 'autoload' value returned by the module's getModuleInfo() method, where higher integers make the module autoload before lower numbers. But autoload core modules still had their file included before site modules, regardless of the autoload setting. I've added an update that lets a module be included (and load) before even the core modules, specifically with this feature request and Tracy in mind. To do it, the module must meet these:

- Module info `autoload` value is integer of 10000 or greater, i.e. `[ 'autoload' => 10000 ]`
- Module info `singular` value must be non-empty, i.e. `[ 'singular' => true ]`
- Module file is located in: /site/modules/ModuleName/ModuleName.module.php 
- Module cannot load any other modules at least until ready() method called. 
- Module cannot have any `requires` dependencies to any other modules. 

In the case of Tracy, I think the only thing needed to enable it to load before other modules is to just change its `getModuleInfo(['autoload'])` value from 9999 to 10000 (or higher). Please let me know if any of you get a chance to try it out, I'm curious if it answers this feature request or if more is needed. 

@adrianbj I was going to also have the ProcessWire namespace be a requirement for loading before core modules, but noticed Tracy isn't in the ProcessWire namespace, so ended up coding around it. Any reason why Tracy is in the root namespace? This means ProcessWire has to compile it. Given that Tracy is fairly large, there could be a significant performance benefit to having it in the ProcessWire namespace.

**Comment by adrianbj** [comment]
Tracy has been using this since it was implemented to the PW core back in September, 2018 :)

However, I have set it to `9999` (https://github.com/adrianbj/TracyDebugger/blob/d29589a4107d01b222cd749412e51362910b1cd4/TracyDebugger.module.php#L31) 

I am just looking at the new commit regarding this (https://github.com/processwire/processwire/commit/c4d301a40530cfa3b00ce559a14757684625a5ce) and it seems that now `10000` is a requirement, so I will update Tracy shortly, but again, should I go for even higher, say `100000`? 

I haven't namespaced any of my modules yet - I didn't want to kill support for PW 2.x while things were working fine. Given that the compiled version is cached, I didn't think there really was any performance hit except for the first load after an update to a module. Is that not the case? Is there a penalty on every load?

**Comment by ryancramerdesign** [comment]
I made it 10000 (1+ what you were using) because I didn't want to have it
automatically apply until you'd had a chance to test it. Though I have
briefly tested it here and so far so good. As for performance hit on
compiled vs non compiled, I think you are probably right that it's likely
not that significant once the files are compiled. But I haven't done a side
by side comparison with TD so I don't know for sure. Of course there is
less overhead with not having to compile, but it may not be that much.

**Comment by adrianbj** [comment]
@ryancramerdesign - I just looked at your latest commit properly and realized this new version allows loading before core modules as well - I didn't realize that before. My quick tests seem like everything is working fine and I've pushed a new version of Tracy with the autoload set to `100000` to leave lots of room for others between `10000` and `100000` :)

Hopefully this change will be helpful for you working on core modules.

**Comment by matjazpotocnik** [comment]
@gideonso, @adrianbj, can we close this feature request?

**Comment by adrianbj** [comment]
Yep, happy for this to be closed.

**Comment by netcarver** [comment]
Done.
