### ISSUE TITLE
add code snippet for dev-config in config.php

### ISSUE THREAD

**Issue by BernhardBaumrock** [processwire/processwire-requests#169]
### Short description of the enhancement

What do you think of adding a code snippet like this to the config.php file?
```
if(strpos($config->paths->root, 'C:/laragon/') === 0) {
  $config->dbUser = 'root';
  $config->dbPass = '';
  $config->httpHosts = array($_SERVER[HTTP_HOST]);
}
```
Of course this should be commented out and with some instructions ("change C:/laragon to your needs"). But for me this is a perfect solution. The check could also be done by the HTTP_HOST.

### Why would the enhancement be useful to users?

Currently we have the config-dev.php file option. I don't think this is ideal. What if this file was uploaded on the live server by accident? Having a separate config-dev.php file also makes it necessary to keep both files in sync. That was my first idea: To include the original config and then overwrite settings. But it's just simpler the other way round: Using the default config.php file and overwriting settings there.

### Optional: Screenshots/Links that demonstrate the enhancement

https://processwire.com/talk/topic/18719-maintain-separate-configs-for-livedev-like-a-boss/

**Comment by gmclelland** [comment]
Here's a related issue that might interest you https://github.com/processwire/processwire-requests/issues/142

**Comment by ethanbeyer** [comment]
Thanks for linking that other thread @gmclelland - I knew I had posted about this before, somewhere. Also from #142:

https://github.com/processwire/processwire-requests/issues/142#issuecomment-351402932

I like this approach because then some things are *never* committed to the repository, and the parts of `config.php` that are "global" don't need to be written twice. Keep it DRY!

**Comment by horst-n** [comment]
I don't think this should be in core.
