### ISSUE TITLE
Focus URL input after CKEditor pwlink modal opens

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#183]
### Short description of the enhancement

When the CKEditor link modal opens (pwlink plugin / ProcessPageEditLink) the "Link to URL" is the main input in the modal (it is open while the other inputfields are closed). As it is the main input it would be useful if it was automatically focused when the modal opens, so the user can begin typing a URL or page title immediately without needing to mouse click or tab to the input.

This could be done by adding the following line [here](https://github.com/processwire/processwire/blob/2cc69a1f0bdd67bba5d3d28fab2dd30a3d7459fb/wire/modules/Inputfield/InputfieldCKEditor/plugins/pwlink/plugin.js#L218):

```js
$i.find('#link_page_url_input').focus();
```

**Comment by teppokoivula** [comment]
I have a bad habit of clicking the link tool and pasting an URL from the clipboard... only to realise that I've just pasted it within the CKEditor content. I know – shouldn't be so hasty. Still, if what @Toutouwai is suggesting here was made the default behaviour, at least in my case it would definitely streamline the editing process and remove one unnecessary click for every link added. So, definitely a +1 :)

Note: not entirely sure if there's another issue at play here as well: when the modal is opened, should the CKEditor edit area remain focused? It does for me at least, causing aforementioned issue. If that's not what others are experiencing, I can open a separate issue for that.

**Comment by ryancramerdesign** [comment]
Thanks, good idea, I have added this. Though I put it in ProcessPageEditLink.js instead. Any reason you think it should be in the CKEditor plugin.js file instead?

**Comment by gmclelland** [comment]
On a related note... Does anyone know of a way to submit the form by pressing the "Enter" key twice after autocompleting a link in the pwlink modal?  Once to select the autocomplete item and the other to insert the link.

I always have to type the name of the page I'm trying to link to, and then select it, and then use my mouse to click the "Insert Link" button because keyboard tabbing is weird in this dialog.

It would be quicker if I could just use my keyboard.  Maybe I need to open a separate issue for this?

**Comment by Toutouwai** [comment]
> Though I put it in ProcessPageEditLink.js instead. Any reason you think it should be in the CKEditor plugin.js file instead?

No, makes sense to add it where you did. Thanks.

> Does anyone know of a way to submit the form by pressing the "Enter" key twice after autocompleting a link in the pwlink modal? Once to select the autocomplete item and the other to insert the link.

It should just be one Enter press because highlighting an item in the autocomplete dropdown already populates the URL input. An Enter press is supposed to close the modal but it's not working because the ID of URL input is wrong (must have changed at some point).

@ryancramerdesign, could you update the line [here](https://github.com/processwire/processwire/blob/e53e4b4bd02ff051d77003a60229e792e6940fde/wire/modules/Inputfield/InputfieldCKEditor/plugins/pwlink/plugin.js#L220) to:

```js
jQuery("#link_page_url_input", $i).keydown(function(event) {
```

**Comment by gmclelland** [comment]
Thanks @Toutouwai 👏 and @ryancramerdesign

**Comment by gmclelland** [comment]
@Toutouwai I just tested your change and it does provide a solution.

This is the way it works:
User types 'about' in the autocomplete.  'About Us' shows in a dropdown.  I use the down key to highlight the 'About Us' page.  Then I press the Enter key to insert the 'About Us' page into the Link to URL field, but then it auto submits the link into the text area.

I'm not sure if it is possible, but I think it would probably be a better UX if the first Enter key press selects the 'About Us' and inserts it into the Link to URL field and then a second Enter key press would submit the link into the text area.  This is how it is handled when using the popular Linkit module in Drupal.  https://www.drupal.org/project/linkit

I say that because the user may want to continue entering other information?

**Comment by Toutouwai** [comment]
> Then I press the Enter key to insert the 'About Us' page into the Link to URL field

This step isn't needed, so one solution is to not do it ;-)

If you want to continue entering other information you just need to unfocus the URL input, by tabbing out of the field or clicking elsewhere in the UI.

It's pretty common (although not always the case) for the Enter key to trigger the submission of a form, which in this case means also closing the modal.

**Comment by ryancramerdesign** [comment]
>  could you update the line here to:

@Toutouwai Thanks I have updated that. You are right the id must have changed, I hadn't noticed before.

**Comment by Toutouwai** [comment]
Great, thanks!
