### ISSUE TITLE
ProcessForgotPassword Logging

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-requests#193]
### Short description of the enhancement

A lot of things are logged by ProcessWire (thank God), but I'm looking for a way to log when a user changes their password using the ProcessForgotPassword module. Somewhere around [Line 340](https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessForgotPassword.module#L340) of this file would be a good place to do so.

```php
if($user->save()) {
  $this->log->save('forgot-password', "Password was reset for {$user->name}");
}
```

### Why would the enhancement be useful to users?

Just further insight to what's going on with user data on live sites.

**Comment by ryancramerdesign** [comment]
That's funny, I've been making lots of updates to this module this week and
I added logging yesterday. :) I need to test some of the other updates
further before pushing to GitHub, but it should be there later this week.

On May 15, 2018 1:35 PM, "Ethan Beyer" <notifications@github.com> wrote:

Short description of the enhancement

A lot of things are logged by ProcessWire (thank God), but I'm looking for
a way to log when a user changes their password using the
ProcessForgotPassword module. Somewhere around Line 340
<https://github.com/processwire/processwire/blob/master/wire/modules/Process/ProcessForgotPassword.module#L340>
of this file would be a good place to do so.

if($user->save()) {  $this->log->save('forgot-password', "Password was
reset for {$user->name}");}

Why would the enhancement be useful to users?

Just further insight to what's going on with user data on live sites.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/processwire/processwire-requests/issues/193>, or mute
the thread

**Comment by ethanbeyer** [comment]
Awesome, thank you!

**Comment by ethanbeyer** [comment]
Thanks for this! I'm marking it as closed since this has been moved to the `dev` branch already.
