### ISSUE TITLE
Support custom fields for images in core

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-requests#21]
### Short description of the enhancement

Support custom fields for images.  ImageExtra module provides this functionality, but it would be great to support this in the core for a more seamless experience.
### Current vs. suggested behavior

n/a
### Why would the enhancement be useful to users?

Oftentimes, custom fields are needed for an image.  Of course, one way around this is to make a repeater that contains an image field with the needed custom fields, but then you lose the nice UI that PW provides for images.

**Comment by Toutouwai** [comment]
FYI: some discussion relating to this subject in the [Visual Page Selector](https://processwire.com/talk/topic/11040-visual-page-selector-commercial-page-picker-module-for-processwire/?do=findComment&comment=129658) forum thread.

**Comment by tiefenb** [comment]
Yeah! I think this is one of the most wanted features! It's on the roadmap for 2018. I hope It comes quick :-)

**Comment by tiefenb** [comment]
Puh - It's 10/27 and this feature is still not here. :-( :-(

**Comment by tiefenb** [comment]
@ryancramerdesign any news on this feature? I'm waiting so hard for this because the 3rth party module "ImageExtra" is now very bugy and I guess the maintainer stopped working in the module.

it's on the pw roadmap since ~2 years.

**Comment by szabeszg** [comment]
@tiefenb Maybe you can give a try to this module: https://processwire.com/talk/topic/21779-repeater-images/

**Comment by tiefenb** [comment]
@szabeszg yes I know that module. I wanted only to grouse a little bit ;-)

When @ryancramerdesign postpones this another year I will do a migration to repeater images but since this is some bigger effort in our existing setup it would be greater to do it with the "native core" feature when it should come in the next time...

**Comment by ethanbeyer** [comment]
Be kind!

**Comment by tiefenb** [comment]
> Be kind!

this is a normal questions about a feature which was announced 2017 for 2018 and now half of 2019 is over.

I know that Ryan makes a great job here. I'm reading every single commit message since ~3 years and happy about it :-) And I know also how Ryan decides which feature comes next or what is to do next.

**Comment by ethanbeyer** [comment]
I hear you. But I said "Be kind!" because the phrase, "When @ryancramerdesign postpones this another year," smacks of a mindset that says you're owed that. And this is just something roadmapped, not necessarily promised. If you want it, at least try writing it yourself and submitting it as a PR.

**Comment by tiefenb** [comment]
> If you want it, at least try writing it yourself and submitting it as a PR.

I think I have not the necessary deep knowledge about the pw core/architecture or in simple words: I guess I'm to dumb for that :-D

**Comment by jlahijani** [comment]
This is now complete.  More info: https://processwire.com/blog/posts/pw-3.0.142/
