### ISSUE TITLE
Is htaccess the only way?

### ISSUE THREAD

**Issue by ethanbeyer** [processwire/processwire-requests#272]
I just posted [this topic](https://processwire.com/talk/topic/20886-processwires-dependence-on-htaccess/) on `/talk`, but wanted to float the question on the repo as well:

> **Does ProcessWire rely on `.htaccess` *too much*?**
> 
> I realize that `.htaccess` handles a lot of baseline security and routing issues within the ProcessWire ecosystem. Inevitably, this leads to a large reliance on Apache, unless one is willing to try to convert those rules to NGINX configurations.
> 
> This has led me to wonder, is there a better way (PHP based?) of handling routing and security than `.htaccess`?

Laravel and Wordpress both handle routing in ways other than ``.htaccess`` - is that possible to achieve with ProcessWire, to make it a little less dependent on certain systems?

**Comment by lesaff** [comment]
@ethanbeyer I use this nginx directives found [here](https://processwire.com/talk/topic/20405-spiria-chooses-processwire/?tab=comments#comment-176997) and it works fine on Laravel Forge.

**Comment by ryancramerdesign** [comment]
Apache can do this stuff a whole lot quicker than PHP can, which ultimately
makes ProcessWire a lot more efficient. As far as security, the .htaccess
rules are largely optional but a very good first line of defense to
eliminate invalid requests rather than having PW spend time with them. As
for routing, I don't know about Laravel, but WordPress at least uses a very
similar strategy of .htaccess passing into PHP.
