### ISSUE TITLE
Add support for easy use of Selectize with InputfieldText

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#301]
### Short description of the enhancement

The use of Selectize in the Files/Images tags input is quite neat. 

![2019-05-16_150456](https://user-images.githubusercontent.com/1538852/57823532-01eff100-77ec-11e9-8a3f-e4ca9d6ad57a.png)

It would be nice if there was an easy way to use Selectize like this with InputfieldText in the admin, so that terms separated with spaces automatically become tags. And you could set some predefined tags too.

I'm imagining some API like this:

```php
$f = $modules->get('InputfieldText');
$f->useTags = true;
$f->predefinedTags = 'one two three';
```

And these would be set as data attributes on the input, with Selectize kicking in whenever the relevant data attributes are present on an input.

There are a few places this could be used in the core (setting the predefined tags for Files/Images fields, the Tags input for fields and templates), and I think it would be a handy feature for third-party module developers too.

**Comment by jlahijani** [comment]
Wow I was literally about to just request this.

Can selectize be an option that can be applied to multi-select Page fields and Select (FieldtypeOptions), mainly as an alternative to ASMSelect?  ASMSelect is great but in some cases it takes up too much horizontal space.

Edit: actually maybe forget this (see next comment instead)

**Comment by jlahijani** [comment]
If implemented for Text fields as @Toutouwai suggested, would it be possible to allow tags to be entered to support value and title?

Take a state selector for example:

- CA|California
- TX|Texas
- NY|New York

In the list of selectable options, it would show "California" for example, but the value saved would be "CA".

Selectize has support this:
https://selectize.github.io/selectize.js/#demo-max-items

Also, possible to do optgroups?

Also, spaces as delimiters might be problematic.  Could the interface for adding selectable options be a big textarea like the "Options" field?

Also, drag-and-drop support?  Selectize already has an option for that too and it relies on jquery sortable which PW is already using. (on the demo page I linked to above, click the "Plugins" tab to see a demo of sortable)

Overall, I think this is a really important enhancement because it avoids the need to use Page or Options fields (since they require more db queries), while still getting some of their benefits.  It's perfect for controlled metadata type stuff.

**Comment by jmartsch** [comment]
As an alternative take a look at https://joshuajohnson.co.uk/Choices/ which has no jQuery dependency, and is similar to selectize. However, it is a little big bigger 22kb compared to 7 KB, but that comes because it's dependency free.

**Comment by szabeszg** [comment]
One more tip: http://slimselectjs.com/
No Dependencies, 20kb - 5kb gzip + lots of features :)

**Comment by teppokoivula** [comment]
Regarding alternatives: it seems very unlikely that we'd be getting rid of jQuery anytime soon in the Admin, so if the main benefit of changing the plugin would be getting rid of the jQuery dependency **and** there would be downsides (API or size related), I'd vote for sticking with the current plugin.

Robin's suggestion here is great – I for one would definitely be using this :)

**Comment by jmartsch** [comment]
Why I brought up the alternative, is because it is future proof. So we could work towards a jQuery free admin. Which could be quicker developed, if most external scripts work without the jQuery dependency.

**Comment by szabeszg** [comment]
While I also linked to a dependency free alternative (which is probably not feature rich enough, so sorry for that), I am not convinced that getting rid of jQuery is the best idea. A "patchwork" of small libs independent of each other has a bigger footprint in terms of bites, since there is no common utility library to cut down on somewhat repeated utilities. A good example is Uikit 3's lib: https://github.com/uikit/uikit-site/blob/feature/js-utils/docs/pages/javascript-utilities.md They state:

> The provided JavaScript utilities allow you to write simplified Vanilla JavaScript and replace the most common functions of jQuery.

uikit.min.js is 134kb, and uikit-icons.min.js is 63kb so I wonder how much is "wasted" by reinventing the wheel here-and-there...

**Comment by Toutouwai** [comment]
This is now possible with [InputfieldTextTags](https://processwire.com/talk/topic/25500-pw-30176-%E2%80%93-core-updates/). Thanks @ryancramerdesign!
