### ISSUE TITLE
multilanguage installer

### ISSUE THREAD

**Issue by clsource** [processwire/processwire-requests#5]
I don´t know if this was requested before.
I think Processwire will benefit if the installer
could be translated in other languages beside english.

Maybe using the native php gettext http://php.net/manual/en/book.gettext.php
or https://code.launchpad.net/php-gettext
just for the installer part. Then using Po and Mo files
will enable translation in other languages.

👍

**Comment by ryancramerdesign** [comment]
Short term I don't think we'll pursue this one just because it would mean using a different translation system/methodology than the rest of PW, and for a file that gets used once and is then deleted. I've also not heard of anyone being unable to install PW as a result of language so far. However, if there turns out to be a lot of demand for it (like for specific languages), we could always look further into it. If we did support it at some point, I'd probably want translations to be self contained within the install.php file rather than have any other external dependencies or files (like po and mo files).

**Comment by clsource** [comment]
I see.
Then the possible approach is having a translated install.php file
for different languages. 

With this approach someone that wants a translated install
just use the proper install.php file.

**Comment by ryancramerdesign** [comment]
That's one way to do it. But rather I was thinking just the old fashioned way of managing translations, like in an associative array in the install.php file. That way the install.php remains singular, self contained, and needs nothing but itself. 

But I'm not convinced that a multi-language installer is worth the resources of implementation because pretty much everything related to PW's documentation, community, not to mention the entirety of HTML/PHP/JS/CSS is already English-based. Our primary audience is the web developer that works with these technologies, and our multi-language focus is about supporting them in creation of multi-language sites.

**Comment by clsource** [comment]
Seems fair enough.
I will close this issue. 
May be in the future this issue could be re opened if the need arise.
👍
